# Generated by Django 5.2.17 on 2026-08-28 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('alt_text', models.CharField(blank=True, help_text='A concise description for people using assistive technology.', max_length=300)),
                ('caption', models.TextField(blank=True)),
                ('photographer_credit', models.CharField(blank=True, max_length=180)),
                ('event_name', models.CharField(blank=True, max_length=180)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rights_status', models.CharField(choices=[('unknown', 'Not assessed'), ('cleared', 'Cleared'), ('restricted', 'Restricted'), ('expired', 'Expired')], default='unknown', max_length=20)),
                ('permitted_use', models.CharField(choices=[('internal', 'Internal use only'), ('editorial', 'Editorial'), ('marketing', 'Marketing'), ('all', 'All approved uses')], default='internal', max_length=20)),
                ('licence_details', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('cloudinary_asset_id', models.CharField(max_length=255, unique=True)),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('delivery_type', models.CharField(default='authenticated', max_length=30)),
                ('secure_url', models.URLField(max_length=1000)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('image_format', models.CharField(max_length=20)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('bytes', models.PositiveBigIntegerField()),
                ('version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assets', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL)),
                ('collections', models.ManyToManyField(blank=True, related_name='assets', to='assets.collection')),
                ('tags', models.ManyToManyField(blank=True, related_name='assets', to='assets.tag')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Metadata updated'), ('submitted', 'Submitted for review'), ('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('archived', 'Archived'), ('restored', 'Restored'), ('downloaded', 'Download link requested')], max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_review', 'In review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('archived', 'Archived')], max_length=24)),
                ('to_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_review', 'In review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('archived', 'Archived')], max_length=24)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_events', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assets.asset')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['asset', '-created_at'], name='asset_event_asset_idx'), models.Index(fields=['actor', '-created_at'], name='asset_event_actor_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', '-created_at'], name='asset_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['uploader', 'status'], name='asset_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['rights_status', 'expiry_date'], name='asset_rights_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['expiry_date'], name='asset_expiry_idx'),
        ),
    ]
